/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CCashierRegister;
import com.mysql.cj.x.protobuf.MysqlxSession;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Timer;
import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author User
 */
public class VCashierRegistation extends javax.swing.JFrame {

    /**
     * Creates new form VCashierRegistation
     */
    public VCashierRegistation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Cas_id = new javax.swing.JTextField();
        txt_job_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_tp = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_u_no = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        txt_pass_con = new javax.swing.JPasswordField();
        btn_reset = new javax.swing.JButton();
        error_user_id = new javax.swing.JTextField();
        error_cashier_id = new javax.swing.JTextField();
        error_job_id = new javax.swing.JTextField();
        error_name = new javax.swing.JTextField();
        error_tp = new javax.swing.JTextField();
        error_passwd = new javax.swing.JTextField();
        error_con_passwd = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 54, 63));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registation Form");

        btn_back.setIcon(new javax.swing.ImageIcon("E:\\My Work\\Netbeans\\EAD - CW\\EAD - CW - 2022-06-09-End\\image\\arrow-small-left.png")); // NOI18N
        btn_back.setBorder(null);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(btn_back)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_back)
                    .addComponent(jLabel1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(198, 201, 209));
        jPanel2.setForeground(new java.awt.Color(204, 0, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cashier ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Job ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Telephone");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Retype Password");

        txt_Cas_id.setBackground(new java.awt.Color(198, 201, 209));
        txt_Cas_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Cas_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Cas_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Cas_idKeyReleased(evt);
            }
        });

        txt_job_id.setBackground(new java.awt.Color(198, 201, 209));
        txt_job_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_job_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_job_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_job_idKeyReleased(evt);
            }
        });

        txt_name.setBackground(new java.awt.Color(198, 201, 209));
        txt_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nameKeyReleased(evt);
            }
        });

        txt_tp.setBackground(new java.awt.Color(198, 201, 209));
        txt_tp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_tp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tpKeyReleased(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(46, 54, 63));
        btn_submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Submitte");
        btn_submit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("User ID");

        txt_u_no.setBackground(new java.awt.Color(198, 201, 209));
        txt_u_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_u_no.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_u_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_noActionPerformed(evt);
            }
        });
        txt_u_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_u_noKeyReleased(evt);
            }
        });

        txt_pass.setBackground(new java.awt.Color(198, 201, 209));
        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
        });

        txt_pass_con.setBackground(new java.awt.Color(198, 201, 209));
        txt_pass_con.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_pass_con.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_pass_con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pass_conKeyReleased(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(46, 54, 63));
        btn_reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        error_user_id.setBackground(new java.awt.Color(198, 201, 209));
        error_user_id.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_user_id.setForeground(new java.awt.Color(204, 0, 51));
        error_user_id.setBorder(null);

        error_cashier_id.setBackground(new java.awt.Color(198, 201, 209));
        error_cashier_id.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_cashier_id.setForeground(new java.awt.Color(204, 0, 51));
        error_cashier_id.setBorder(null);

        error_job_id.setBackground(new java.awt.Color(198, 201, 209));
        error_job_id.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_job_id.setForeground(new java.awt.Color(204, 0, 51));
        error_job_id.setBorder(null);

        error_name.setBackground(new java.awt.Color(198, 201, 209));
        error_name.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_name.setForeground(new java.awt.Color(204, 0, 51));
        error_name.setBorder(null);

        error_tp.setBackground(new java.awt.Color(198, 201, 209));
        error_tp.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_tp.setForeground(new java.awt.Color(204, 0, 51));
        error_tp.setBorder(null);

        error_passwd.setBackground(new java.awt.Color(198, 201, 209));
        error_passwd.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_passwd.setForeground(new java.awt.Color(204, 0, 51));
        error_passwd.setBorder(null);

        error_con_passwd.setBackground(new java.awt.Color(198, 201, 209));
        error_con_passwd.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        error_con_passwd.setForeground(new java.awt.Color(204, 0, 51));
        error_con_passwd.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_u_no, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txt_Cas_id)
                            .addComponent(txt_job_id)
                            .addComponent(txt_name)
                            .addComponent(txt_tp)
                            .addComponent(txt_pass)
                            .addComponent(txt_pass_con)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error_con_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_tp, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_name, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_job_id, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_cashier_id, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_u_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Cas_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(error_cashier_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_job_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_job_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_con_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 54, 63));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try{
            if(txt_u_no.getText().isEmpty()==true){
                error_user_id.setText("User ID Cannot be Blank");
            }
            else if(txt_Cas_id.getText().isEmpty()==true){
                error_cashier_id.setText("Cashier ID cannot Blank");
            }
            else if(txt_job_id.getText().isEmpty()==true){
                error_job_id.setText("Job ID cannot Blank");
            }
            else if(txt_name.getText().isEmpty()==true){
                error_name.setText("Name cannot Blank");
            }
            else if(txt_tp.getText().isEmpty()==true){
                error_tp.setText("Telephone number cannot Blank");
            }
            else if(txt_pass.getText().isEmpty()==true){
                error_passwd.setText("Password cannot Blank");
            }
            else if(txt_pass_con.getText().isEmpty()==true){
                error_con_passwd.setText("Confirm Password cannot Blank");
            }
            else{
                int cashier_id,job_id,tp,password,conpassword;
                String u_number,name,user_type;
                
                u_number=txt_u_no.getText();
                cashier_id=Integer.parseInt(txt_Cas_id.getText());
                    job_id=Integer.parseInt(txt_job_id.getText());
                name=txt_name.getText();
                tp=Integer.parseInt(txt_tp.getText());
                password=Integer.parseInt(txt_pass.getText());
                conpassword=Integer.parseInt(txt_pass_con.getText());
                user_type="Cashier";
            
                if(password==conpassword){
                CCashierRegister log1=new CCashierRegister();
                log1.getLogin(u_number,cashier_id,job_id,name,tp,password,user_type);
                log1.setLogin(u_number,name,tp,password,user_type);
                clear();}
                else {
                JOptionPane.showMessageDialog(null,"Pleasse check again");
        }
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error !",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
            clear();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        VloginForm d=new VloginForm();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    
    //-------------------------------------------------Regex Validation --------------------------------------------------------------------//
    
    
    private void txt_u_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_u_noKeyReleased
        String PATTERN="^[a-zA-Z0-9]{0,5}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_u_no.getText());
        if(!match.matches()){
            error_user_id.setText("* Cannot Apply Special caracter");
        }
        else {
            error_user_id.setText(null);
        }
        
    }//GEN-LAST:event_txt_u_noKeyReleased

    private void txt_Cas_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Cas_idKeyReleased
        String PATTERN="^[0-9]{0,5}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_Cas_id.getText());
        if(!match.matches()){
            error_cashier_id.setText("* Integear value only");
        }
        else {
            error_cashier_id.setText(null);
        }
    }//GEN-LAST:event_txt_Cas_idKeyReleased

    private void txt_job_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_job_idKeyReleased
        String PATTERN="^[0-9]{0,5}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_job_id.getText());
        if(!match.matches()){
            error_job_id.setText("* Integear value only");
        }
        else {
            error_job_id.setText(null);
        }
    }//GEN-LAST:event_txt_job_idKeyReleased

    private void txt_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyReleased
        String PATTERN="^[a-zA-Z]{0,18}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_name.getText());
        if(!match.matches()){
            error_name.setText("* Digits Only");
        }
        else {
            error_name.setText(null);
        }
    }//GEN-LAST:event_txt_nameKeyReleased

    private void txt_tpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tpKeyReleased
        String PATTERN="^[0-9]{0,12}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_tp.getText());
        if(!match.matches()){
            error_tp.setText("* Integear value only");
        }
        else {
            error_tp.setText(null);
        }
    }//GEN-LAST:event_txt_tpKeyReleased

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        String PATTERN="^[0-9]{0,5}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_pass.getText());
        if(!match.matches()){
            error_passwd.setText("* Integear value only");
        }
        else {
            error_passwd.setText(null);
        }
    }//GEN-LAST:event_txt_passKeyReleased

    private void txt_pass_conKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pass_conKeyReleased
        String PATTERN="^[0-9]{0,5}$";
        Pattern Patt=Pattern.compile(PATTERN);
        Matcher match=Patt.matcher(txt_pass_con.getText());
        if(!match.matches()){
            error_con_passwd.setText("* Integear value only");
        }
        else {
            error_con_passwd.setText(null);
        }
    }//GEN-LAST:event_txt_pass_conKeyReleased

    private void txt_u_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_noActionPerformed
    
    
    
    //-----------------------------------------------------------Clear ------------------------------------------------------------------//
    
    
    
   public void clear(){
       txt_u_no.setText("");
       txt_Cas_id.setText("");
       txt_job_id.setText("");
       txt_name.setText("");
       txt_tp.setText("");
       txt_pass.setText("");
       txt_pass_con.setText("");
       error_cashier_id.setText("");
       error_con_passwd.setText("");
       error_job_id.setText("");
       error_name.setText("");
       error_passwd.setText("");
       error_tp.setText("");
       error_user_id.setText("");
   }
   
   
    //-------------------------------------------------------------------------------------------------------------------------------------------------//
   
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCashierRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCashierRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCashierRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCashierRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCashierRegistation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_submit;
    private javax.swing.JTextField error_cashier_id;
    private javax.swing.JTextField error_con_passwd;
    private javax.swing.JTextField error_job_id;
    private javax.swing.JTextField error_name;
    private javax.swing.JTextField error_passwd;
    private javax.swing.JTextField error_tp;
    private javax.swing.JTextField error_user_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_Cas_id;
    private javax.swing.JTextField txt_job_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_pass_con;
    private javax.swing.JTextField txt_tp;
    private javax.swing.JTextField txt_u_no;
    // End of variables declaration//GEN-END:variables
}
